# Site settings
title: angel k brown 
email: angelkbrown@gmail.com 
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://angelkbrown.com" # the base hostname & protocol for your site
twitter_username: _akbrown
github_username:  angelkbrown
linkedin_username: angelkbrown
# Build settings
markdown: kramdown
